# Generated by Django 5.2.8 on 2025-11-26 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='greetings/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='greetings/images/')),
                ('birthday_date', models.DateField()),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('bright', 'Bright'), ('friendly', 'Friendly'), ('lovely', 'Lovely'), ('romantic', 'Romantic'), ('casual', 'Casual'), ('proposing', 'Proposing'), ('partner', 'Partner')], default='lovely', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_greetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday Greeting',
                'verbose_name_plural': 'Birthday Greetings',
                'ordering': ['-created_date'],
            },
        ),
    ]
