# Generated by Django 5.2.8 on 2025-11-26 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greeting',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='greeting',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='greeting',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark 🌙'), ('bright', 'Bright ☀️'), ('friendly', 'Friendly 😊'), ('lovely', 'Lovely 💕'), ('romantic', 'Romantic 💑'), ('casual', 'Casual 🤙'), ('proposing', 'Proposing 💍'), ('partner', 'Partner 👫')], default='lovely', max_length=20),
        ),
        migrations.AddIndex(
            model_name='greeting',
            index=models.Index(fields=['sender', '-created_date'], name='greetings_g_sender__09e00e_idx'),
        ),
        migrations.AddIndex(
            model_name='greeting',
            index=models.Index(fields=['unique_id'], name='greetings_g_unique__670020_idx'),
        ),
        migrations.AddIndex(
            model_name='greeting',
            index=models.Index(fields=['theme'], name='greetings_g_theme_aac95b_idx'),
        ),
    ]
